/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as DemoAiStructuredRouteImport } from './routes/demo/ai-structured'
import { Route as DemoAiImageRouteImport } from './routes/demo/ai-image'
import { Route as DemoAiChatRouteImport } from './routes/demo/ai-chat'
import { Route as ApiSyncRouteRouteImport } from './routes/api/sync/route'
import { Route as ApiOrdersRouteRouteImport } from './routes/api/orders/route'
import { Route as ApiBotsRouteRouteImport } from './routes/api/bots/route'
import { Route as DemoGuitarsIndexRouteImport } from './routes/demo/guitars/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoGuitarsGuitarIdRouteImport } from './routes/demo/guitars/$guitarId'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOrdersIdRouteRouteImport } from './routes/api/orders/$id/route'
import { Route as ApiBotsIdRouteRouteImport } from './routes/api/bots/$id/route'
import { Route as ApiAuthLoginRouteRouteImport } from './routes/api/auth/login/route'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as DemoApiAiTtsRouteImport } from './routes/demo/api.ai.tts'
import { Route as DemoApiAiTranscriptionRouteImport } from './routes/demo/api.ai.transcription'
import { Route as DemoApiAiStructuredRouteImport } from './routes/demo/api.ai.structured'
import { Route as DemoApiAiImageRouteImport } from './routes/demo/api.ai.image'
import { Route as DemoApiAiChatRouteImport } from './routes/demo/api.ai.chat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiStructuredRoute = DemoAiStructuredRouteImport.update({
  id: '/demo/ai-structured',
  path: '/demo/ai-structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiImageRoute = DemoAiImageRouteImport.update({
  id: '/demo/ai-image',
  path: '/demo/ai-image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiChatRoute = DemoAiChatRouteImport.update({
  id: '/demo/ai-chat',
  path: '/demo/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRouteRoute = ApiSyncRouteRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRouteRoute = ApiOrdersRouteRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsRouteRoute = ApiBotsRouteRouteImport.update({
  id: '/api/bots',
  path: '/api/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGuitarsIndexRoute = DemoGuitarsIndexRouteImport.update({
  id: '/demo/guitars/',
  path: '/demo/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGuitarsGuitarIdRoute = DemoGuitarsGuitarIdRouteImport.update({
  id: '/demo/guitars/$guitarId',
  path: '/demo/guitars/$guitarId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersIdRouteRoute = ApiOrdersIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiOrdersRouteRoute,
} as any)
const ApiBotsIdRouteRoute = ApiBotsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiBotsRouteRoute,
} as any)
const ApiAuthLoginRouteRoute = ApiAuthLoginRouteRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiTtsRoute = DemoApiAiTtsRouteImport.update({
  id: '/demo/api/ai/tts',
  path: '/demo/api/ai/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiTranscriptionRoute = DemoApiAiTranscriptionRouteImport.update({
  id: '/demo/api/ai/transcription',
  path: '/demo/api/ai/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiStructuredRoute = DemoApiAiStructuredRouteImport.update({
  id: '/demo/api/ai/structured',
  path: '/demo/api/ai/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiImageRoute = DemoApiAiImageRouteImport.update({
  id: '/demo/api/ai/image',
  path: '/demo/api/ai/image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiChatRoute = DemoApiAiChatRouteImport.update({
  id: '/demo/api/ai/chat',
  path: '/demo/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/bots': typeof ApiBotsRouteRouteWithChildren
  '/api/orders': typeof ApiOrdersRouteRouteWithChildren
  '/api/sync': typeof ApiSyncRouteRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/login': typeof ApiAuthLoginRouteRoute
  '/api/bots/$id': typeof ApiBotsIdRouteRoute
  '/api/orders/$id': typeof ApiOrdersIdRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/bots': typeof ApiBotsRouteRouteWithChildren
  '/api/orders': typeof ApiOrdersRouteRouteWithChildren
  '/api/sync': typeof ApiSyncRouteRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/login': typeof ApiAuthLoginRouteRoute
  '/api/bots/$id': typeof ApiBotsIdRouteRoute
  '/api/orders/$id': typeof ApiOrdersIdRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/guitars': typeof DemoGuitarsIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/bots': typeof ApiBotsRouteRouteWithChildren
  '/api/orders': typeof ApiOrdersRouteRouteWithChildren
  '/api/sync': typeof ApiSyncRouteRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/login': typeof ApiAuthLoginRouteRoute
  '/api/bots/$id': typeof ApiBotsIdRouteRoute
  '/api/orders/$id': typeof ApiOrdersIdRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/bots'
    | '/api/orders'
    | '/api/sync'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/better-auth'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/api/auth/login'
    | '/api/bots/$id'
    | '/api/orders/$id'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/guitars/$guitarId'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/guitars/'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/bots'
    | '/api/orders'
    | '/api/sync'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/better-auth'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/api/auth/login'
    | '/api/bots/$id'
    | '/api/orders/$id'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/guitars/$guitarId'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/guitars'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/bots'
    | '/api/orders'
    | '/api/sync'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/better-auth'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/api/auth/login'
    | '/api/bots/$id'
    | '/api/orders/$id'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/guitars/$guitarId'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/guitars/'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiBotsRouteRoute: typeof ApiBotsRouteRouteWithChildren
  ApiOrdersRouteRoute: typeof ApiOrdersRouteRouteWithChildren
  ApiSyncRouteRoute: typeof ApiSyncRouteRoute
  DemoAiChatRoute: typeof DemoAiChatRoute
  DemoAiImageRoute: typeof DemoAiImageRoute
  DemoAiStructuredRoute: typeof DemoAiStructuredRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthLoginRouteRoute: typeof ApiAuthLoginRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoGuitarsGuitarIdRoute: typeof DemoGuitarsGuitarIdRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoGuitarsIndexRoute: typeof DemoGuitarsIndexRoute
  DemoApiAiChatRoute: typeof DemoApiAiChatRoute
  DemoApiAiImageRoute: typeof DemoApiAiImageRoute
  DemoApiAiStructuredRoute: typeof DemoApiAiStructuredRoute
  DemoApiAiTranscriptionRoute: typeof DemoApiAiTranscriptionRoute
  DemoApiAiTtsRoute: typeof DemoApiAiTtsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-structured': {
      id: '/demo/ai-structured'
      path: '/demo/ai-structured'
      fullPath: '/demo/ai-structured'
      preLoaderRoute: typeof DemoAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-image': {
      id: '/demo/ai-image'
      path: '/demo/ai-image'
      fullPath: '/demo/ai-image'
      preLoaderRoute: typeof DemoAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-chat': {
      id: '/demo/ai-chat'
      path: '/demo/ai-chat'
      fullPath: '/demo/ai-chat'
      preLoaderRoute: typeof DemoAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots': {
      id: '/api/bots'
      path: '/api/bots'
      fullPath: '/api/bots'
      preLoaderRoute: typeof ApiBotsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/guitars/': {
      id: '/demo/guitars/'
      path: '/demo/guitars'
      fullPath: '/demo/guitars/'
      preLoaderRoute: typeof DemoGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/guitars/$guitarId': {
      id: '/demo/guitars/$guitarId'
      path: '/demo/guitars/$guitarId'
      fullPath: '/demo/guitars/$guitarId'
      preLoaderRoute: typeof DemoGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$id': {
      id: '/api/orders/$id'
      path: '/$id'
      fullPath: '/api/orders/$id'
      preLoaderRoute: typeof ApiOrdersIdRouteRouteImport
      parentRoute: typeof ApiOrdersRouteRoute
    }
    '/api/bots/$id': {
      id: '/api/bots/$id'
      path: '/$id'
      fullPath: '/api/bots/$id'
      preLoaderRoute: typeof ApiBotsIdRouteRouteImport
      parentRoute: typeof ApiBotsRouteRoute
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/tts': {
      id: '/demo/api/ai/tts'
      path: '/demo/api/ai/tts'
      fullPath: '/demo/api/ai/tts'
      preLoaderRoute: typeof DemoApiAiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/transcription': {
      id: '/demo/api/ai/transcription'
      path: '/demo/api/ai/transcription'
      fullPath: '/demo/api/ai/transcription'
      preLoaderRoute: typeof DemoApiAiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/structured': {
      id: '/demo/api/ai/structured'
      path: '/demo/api/ai/structured'
      fullPath: '/demo/api/ai/structured'
      preLoaderRoute: typeof DemoApiAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/image': {
      id: '/demo/api/ai/image'
      path: '/demo/api/ai/image'
      fullPath: '/demo/api/ai/image'
      preLoaderRoute: typeof DemoApiAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/chat': {
      id: '/demo/api/ai/chat'
      path: '/demo/api/ai/chat'
      fullPath: '/demo/api/ai/chat'
      preLoaderRoute: typeof DemoApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiBotsRouteRouteChildren {
  ApiBotsIdRouteRoute: typeof ApiBotsIdRouteRoute
}

const ApiBotsRouteRouteChildren: ApiBotsRouteRouteChildren = {
  ApiBotsIdRouteRoute: ApiBotsIdRouteRoute,
}

const ApiBotsRouteRouteWithChildren = ApiBotsRouteRoute._addFileChildren(
  ApiBotsRouteRouteChildren,
)

interface ApiOrdersRouteRouteChildren {
  ApiOrdersIdRouteRoute: typeof ApiOrdersIdRouteRoute
}

const ApiOrdersRouteRouteChildren: ApiOrdersRouteRouteChildren = {
  ApiOrdersIdRouteRoute: ApiOrdersIdRouteRoute,
}

const ApiOrdersRouteRouteWithChildren = ApiOrdersRouteRoute._addFileChildren(
  ApiOrdersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiBotsRouteRoute: ApiBotsRouteRouteWithChildren,
  ApiOrdersRouteRoute: ApiOrdersRouteRouteWithChildren,
  ApiSyncRouteRoute: ApiSyncRouteRoute,
  DemoAiChatRoute: DemoAiChatRoute,
  DemoAiImageRoute: DemoAiImageRoute,
  DemoAiStructuredRoute: DemoAiStructuredRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthLoginRouteRoute: ApiAuthLoginRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoGuitarsGuitarIdRoute: DemoGuitarsGuitarIdRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoGuitarsIndexRoute: DemoGuitarsIndexRoute,
  DemoApiAiChatRoute: DemoApiAiChatRoute,
  DemoApiAiImageRoute: DemoApiAiImageRoute,
  DemoApiAiStructuredRoute: DemoApiAiStructuredRoute,
  DemoApiAiTranscriptionRoute: DemoApiAiTranscriptionRoute,
  DemoApiAiTtsRoute: DemoApiAiTtsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
